In [28]:
import pandas as pd

In [29]:
df = pd.read_csv('/content/Task.csv')
df

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes

In [31]:
df.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [32]:
df['Age'].unique()

array([44., 27., 30., 38., 40., 35., nan, 48., 50., 37.])

In [33]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Age']=df['Age'].astype('int')

In [34]:
df.isnull().sum()

Country      0
Age          0
Salary       1
Purchased    0
dtype: int64

In [35]:
df['Salary'].unique()

array([72000., 48000., 54000., 61000.,    nan, 58000., 52000., 79000.,
       83000., 67000.])

In [36]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['Salary']=df['Salary'].astype('int')

In [37]:
df.head()

   Country  Age  Salary Purchased
0   France   44   72000        No
1    Spain   27   48000       Yes
2  Germany   30   54000        No
3    Spain   38   61000        No
4  Germany   40   63777       Yes

In [38]:
df.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    10 non-null     object
 1   Age        10 non-null     int64
 2   Salary     10 non-null     int64
 3   Purchased  10 non-null     object
dtypes: int64(2), object(2)
memory usage: 448.0+ bytes

In [40]:
df['Country'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [41]:
df['Country'].replace({'France':1 , 'Spain':2 , 'Germany':3} , inplace=True)

<ipython-input-41-e08fb0db3b8c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Country'].replace({'France':1 , 'Spain':2 , 'Germany':3} , inplace=True)
<ipython-input-41-e08fb0db3b8c>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Country'].replace({'France':1 , 'Spain':2 , 'Germany':3} , inplace=True)

In [42]:
df.head()

   Country  Age  Salary Purchased
0        1   44   72000        No
1        2   27   48000       Yes
2        3   30   54000        No
3        2   38   61000        No
4        3   40   63777       Yes

In [43]:
df['Purchased'].replace({'No':0 , 'Yes':1} , inplace=True)

<ipython-input-43-40b5c4a44135>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Purchased'].replace({'No':0 , 'Yes':1} , inplace=True)
<ipython-input-43-40b5c4a44135>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Purchased'].replace({'No':0 , 'Yes':1} , inplace=True)

In [46]:
df

   Country  Age  Salary  Purchased
0        1   44   72000          0
1        2   27   48000          1
2        3   30   54000          0
3        2   38   61000          0
4        3   40   63777          1
5        1   35   58000          1
6        2   38   52000          0
7        1   48   79000          1
8        3   50   83000          0
9        1   37   67000          1